### PR TITLE
Implementation for sharded multi res mesh generation with offsets

### PR DESCRIPTION
**Pull request by SridharJagannathan**
Implemented for solving:
#475

### CODE REVIEW

**Comment by SridharJagannathan** [comment]
In principle this seems to work. 
I have just made multi res meshes of the antenna lobe (left, right) in the sharded format. 
I need to just solve the test error and some docs now..
Screenshot 2021-06-08 at 12 49 17

**Comment by william-silversmith** [comment]
This looks great! Just one style point, would you mind changing `dataoffset` to `data_offset`? Other than that, I'm ready to merge.

**Comment by SridharJagannathan** [comment]
Done!

**Comment by william-silversmith** [comment]
Thank you so much! When you've finished your multi-res code, would there be a public place where I could take a look? Merging.

**Review by william-silversmith — APPROVED** [review]

**Comment by SridharJagannathan** [comment]
@william-silversmith: The implementation is composed of two parts:
1) The mutli-res mesh generation is here: https://github.com/SridharJagannathan/pyroglancer/blob/master/pyroglancer/meshgenerator.py
this was based on the discussions in a neuroglancer thread a while ago, which i adapted a bit.
2) The binary file generation for multi-res sharded is here:
   https://github.com/SridharJagannathan/pyroglancer/blob/master/pyroglancer/volumes.py#L146
Hope it is helpful for you.

**Pull request merged**
