### PR TITLE
fix (graphene): check spec exists up to max_meshed_layer

### PR DESCRIPTION
**Pull request by akhileshh**

### CODE REVIEW

**Comment by william-silversmith** [comment]
Hi Akhilesh! Something I am not sure of, if a level > max_meshed_layer is requested, are the meshes that will be requested guaranteed to come from the max_meshed_layer?

**Comment by akhileshh** [comment]
From the chunkedgraph server, yes, it starts including IDs in the manifest only from the max_meshed_layer, and iteratively goes down.

**Review by william-silversmith — APPROVED** [review]

**Comment by william-silversmith** [comment]
I'll make a new release in a bit.

**Comment by jefferis** [comment]
@william-silversmith After updating to cloudvolume 8.16.0 I am seeing this when trying to download flywire meshes:

  AttributeError: 'GrapheneMeshMetadata' object has no attribute 'max_meshed_layer'

I can't quite figure out if these changes are a likely cause or consequence of this PR?

**Comment by william-silversmith** [comment]
Hi Greg, that's almost certainly the case. Sorry about that! I'll have a
fix out by Monday I expect.

**Comment by akhileshh** [comment]
Oh sorry about that. Looks like `max_meshed_layer` is in `GrapheneMetadata`, I thought it was part of mesh meta like in the chunkedgraph code. Should have checked in any case.

@william-silversmith let me know if this is correct, I can submit a new pr.

**Pull request merged**
