### PR TITLE
feat: add cave-secret.json and allow for fqdn qualification

### LINKED ISSUE #458: Support Multiple Graphene Server Tokens
We want to support multiple graph servers as there are now multiple copies in deployment.

The graphene team has also suggested that we revise `chunked-graph.json` to `cave.json`. 

CAVE: Connectome Annotation Versioning Engine  

We'll want to support a similar scheme to google and aws where we append a specifier to the file name. In the case of CAVE, we'll use the domain name.

```cave-some.server.com.json```

The dot structure is awkward, but what can you do. Replacing the dots with e.g. hyphens would mean another server could stand in for the original.

### PR DESCRIPTION
**Pull request by william-silversmith**
e.g. flywire.dynamicannotationframework.com-cave-secret.json
(fake example)

Also adds the ability to configure the `.cloudvolume` directory via an environment variable `CLOUD_VOLUME_DIR`

Resolves #458

### CODE REVIEW

**Comment by ceesem** [comment]
Hi Will,

These changes look extremely promising — I just wanted to mention that, since we use the same token for all of our services, it would be nice if you could give Sven/Forrest/me a heads-up before making a release with this PR so we can get a release of our FrameworkClient ready with the same logic integrated. It should be a quick change, but could cause a lot of confusion if things get out of sync.

**Comment by william-silversmith** [comment]
This change should be backwards compatible so there shouldn't be a disruption I think?

**Comment by william-silversmith** [comment]
@ceesem do you think releasing this would interfere with potential upgrades in the future?

**Comment by ceesem** [comment]
I don't think so — we talked about this and decided that the right place for dealing with the endpoint logic is elsewhere. Please feel free to go ahead.

**Comment by william-silversmith** [comment]
Thanks Casey!

Failing tests are not relevant. I should schedule some time to fix them.

**Pull request merged**
