### PR TITLE
fix: raise errors from cloud files download

### PR DESCRIPTION
**Pull request by william-silversmith**
rx was not checking the cloud files error.

This raise is not behind a retry, so it should kill the process.

### CODE REVIEW

**Review by nkemnitz — COMMENTED** [review]
That should work.
Are there other storage formats / data types that are doing something similar?

**Comment by william-silversmith** [comment]
At least for that example, we're safe. It called `cv.cache.download` which has the proper checks.

https://github.com/seung-lab/cloud-volume/blob/7b13d70c823e0af4987b13f0b2086fc337029b04/cloudvolume/cacheservice.py#L477-L487 

Really, I should have a flag for CloudFiles that automatically raises errors. It should be enabled by default.

**Comment by william-silversmith** [comment]
I worked something up here: https://github.com/seung-lab/cloud-files/pull/57

**Comment by william-silversmith** [comment]
This is covered by the update of cloud-files to 2.0.0 which raises errors by default.

**Pull request closed without merging**
