### PR TITLE
[WIP] HTTP/2 support for HttpInterface

### PR DESCRIPTION
**Pull request by nkemnitz**
Work in progress, but would be nice to get your feedback.

- Added Connection Pool for HttpInterface
  - required for HTTP/2
  - provides speed boost for HTTP1.1 as well - the otherwise repeated SSL handshakes are omitted

- Replaces `requests` package with `hyper` for HTTP/2 support with request streams
  - also had to add some additional / more specific error handling logic, which should help with #148 and #172

Todo:
- Better Exception messages (hyper `Response`s do not include the `Request` method and URL, for example)
- Modify `files_exist` method to use a queue, in order to keep the request streams constantly filled (instead of processing batches of 100)
- Unit Tests for `files_exist` method for both, HTTP1.1 and HTTP2.0 connections
- specialized `get_files` method to quickly *download* multiple files with the `HttpInterface`

### CODE REVIEW

**Comment by william-silversmith** [comment]
This is cool! What kind of perf benefits are you seeing off hand?

**Comment by nkemnitz** [comment]
Results for benchmarking the `files_exist` methods for random keys from our lab to US-EAST1.
- Google seems to limit HTTP/2 to 100 streams on their side
- Multi-_threading_ doesn't help HTTP/2 in this scenario... might be that we are CPU bound now?

|  | n_threads=0 |   |   |   |   | n_threads=20  |  |  |  |
|--:| --:| --:| --:| --:| --:| --:|--:|--:|--:|
|**# Files** | **GCS** | **HTTP/1.1 Old** | **HTTP/1.1 New** | **HTTP/2** |   | **GCS** | **HTTP/1.1 Old** | **HTTP/1.1 New** | **HTTP/2**
|1 | 0.06 | 0.09 | 0.05 | 0.05   | | 0.10 | 0.09 | 0.08 | 0.10
|2 | 0.07 | 0.18 | 0.10 | 0.04   | | 0.10 | 0.10 | 0.10 | 0.10
|3 | 0.07 | 0.26 | 0.19 | 0.09   | | 0.10 | 0.10 | 0.10 | 0.10
|4 | 0.07 | 0.36 | 0.25 | 0.09   | | 0.10 | 0.10 | 0.10 | 0.10
|5 | 0.08 | 0.43 | 0.32 | 0.09   | | 0.10 | 0.11 | 0.10 | 0.10
|6 | 0.08 | 0.53 | 0.45 | 0.09   | | 0.10 | 0.11 | 0.10 | 0.10
|7 | 0.07 | 0.62 | 0.53 | 0.09   | | 0.10 | 0.12 | 0.10 | 0.10
|8 | 0.09 | 0.71 | 0.59 | 0.10   | | 0.10 | 0.12 | 0.10 | 0.10
|9 | 0.09 | 0.79 | 0.65 | 0.10   | | 0.10 | 0.13 | 0.10 | 0.10
|10 | 0.09 | 0.87 | 0.76 | 0.06   | | 0.11 | 0.13 | 0.10 | 0.10
|15 | 0.1 | 1.29 | 1.09 | 0.08   | | 0.12 | 0.16 | 0.10 | 0.10
|20 | 0.14 | 1.65 | 1.51 | 0.08   | | 0.15 | 0.18 | 0.10 | 0.10
|25 | 0.15 | 2.24 | 1.89 | 0.09   | | 0.17 | 0.27 | 0.17 | 0.10
|30 | 0.18 | 2.64 | 2.30 | 0.09   | | 0.16 | 0.29 | 0.17 | 0.10
|40 | 0.25 | 3.51 | 3.10 | 0.11   | | 0.18 | 0.32 | 0.17 | 0.10
|50 | 0.32 | 4.43 | 4.03 | 0.11   | | 0.18 | 0.43 | 0.25 | 0.10
|60 | 0.23 | 5.25 | 4.80 | 0.12   | | 0.18 | 0.46 | 0.26 | 0.11
|70 | 0.4 | 6.24 | 5.51 | 0.15   | | 0.20 | 0.56 | 0.34 | 0.13
|80 | 0.35 | 7.16 | 6.32 | 0.14   | | 0.20 | 0.65 | 0.34 | 0.14
|90 | 0.44 | 7.93 | 7.00 | 0.17   | | 0.22 | 0.74 | 0.42 | 0.18
|100 | 0.48 | 8.75 | 7.81 | 0.16   | | 0.22 | 0.81 | 0.43 | 0.18
|200 | 0.97 | 17.98 | 15.75 | 0.33   | | 0.31 | 1.51 | 0.84 | 0.34
|300 | 0.93 | 27.11 | 23.10 | 0.49   | | 0.36 | 2.18 | 1.25 | 0.51
|400 | 1.67 |   | 32.58 | 0.60 | | 0.44 | 2.88 | 1.66 | 0.61
|500 | 2.47 |   | 39.85 | 0.83 | | 0.51  | 3.65 | 2.08 | 0.81
|600 | 2.29 |   | 48.73 | 1.02 | | 0.59  | 4.33 | 2.53 | 0.97
|700 | 2.77 |   | 56.58 | 1.11 | | 0.63  | 5.16 | 2.91 | 1.16
|800 | 3.96 |   | 63.76 | 1.16 | | 0.71  | 5.96 | 3.33 | 1.34
|900 | 3.82 |   | 72.29 | 1.51 | | 0.77 | 6.69 | 3.75 | 1.47
|1000 | 3.68 |   | 80.64 | 1.52 | | 0.74  | 7.33 | 4.24 | 1.62

**Comment by william-silversmith** [comment]
Closing due to lack of activity and the fact that multi-threaded performance seems to be worse than existing performance.

**Comment by nkemnitz** [comment]
Yeah, it's not a priority for us anymore, and the https://github.com/python-hyper/hyper package appears to be unmaintained.
Regarding performance, you mean the multi-threaded version is not faster than using the GCS interface? Are public datasets (HTTP) always accessible using the GCS interface, or are there situations when users can _only_ use the HTTP interface?

**Comment by nkemnitz** [comment]
https://github.com/encode/httpx might be a suitable alternative to hyper

**Comment by william-silversmith** [comment]
I was thinking of the GCS interface. GCS requires an auth token to use, so HTTP-only is a thing. I wonder why GCS is faster...

**Pull request closed without merging**
