### PR TITLE
fix: only reset connection pool when unpicking on a new PID

### PR DESCRIPTION
**Pull request by william-silversmith**
See discussion on #142

### CODE REVIEW

**Comment by wongwill86** [comment]
👍 looks great!

**Comment by william-silversmith** [comment]
The python2 issue comes from using urllib3==1.24 I'll set the requirement to 1.23

**Comment by william-silversmith** [comment]
fwiw, looks like 1.24 was released 2 hrs ago

**Comment by william-silversmith** [comment]
See discussion here: https://github.com/urllib3/urllib3/issues/1456

Requests is only compatible up to urllib3 1.23. Let's stick with 1.23 for now.

**Pull request merged**
